### PR TITLE
[WIP] Port ompl_interface

### PR DESCRIPTION
**Pull request by anasarrak**

### CODE REVIEW

**Comment by anasarrak** [comment]
Before merging this has to be fixed 
https://github.com/AcutronicRobotics/moveit2/blob/2df13bfe73c1f816ef2cca476dc981c734e98c40/moveit_planners/ompl/ompl_interface/src/ompl_interface.cpp#L211-L221

**Comment by anasarrak** [comment]
I have fixed https://github.com/AcutronicRobotics/moveit2/pull/64#issuecomment-489996672 problem, It gets the parameters from https://github.com/AcutronicRobotics/MARA_ROS1/blob/master/mara_moveit_config/config/ompl_planning.yaml, taking into account that the structure for ros2 has changed, we have to add the following to the top of file:
```
node_name:
  ros__parameters:
    planner_configs:
```

The commits related to the change:
- https://github.com/AcutronicRobotics/moveit2/pull/64/commits/44e7c177844bb4ac3c3d9665d1aa4f13366a519a
- https://github.com/AcutronicRobotics/moveit2/pull/64/commits/c22c50c34ca7f873d6a0065119bbe1defe102d27

**Comment by vmayoral** [comment]
@anasarrak, what's the status of this? can you rebase the work here or should we discard it?

**Comment by anasarrak** [comment]
We can close it, @ahcorde has cherry-picked the commits

**Pull request closed without merging**
