### PR TITLE
Master sync 30 03 19

### PR DESCRIPTION
**Pull request by vmayoral**
I've merged our `master` branch with the last changes from the ros-planning repo. There's been some changes in the CI that might affect our internal testing. https://github.com/AcutronicRobotics/moveit2/tree/master-sync-30-03-19

### CODE REVIEW

**Comment by vmayoral** [comment]
@LanderU can you review that these changes don't break anything in our own CI testing please?

**Comment by vmayoral** [comment]
https://travis-ci.org/AcutronicRobotics/moveit2/builds/513398022?utm_source=github_status&utm_medium=notification passed so I think we're good to go.

I'll accept it but feel free to raise a flag if you see something wrong @LanderU.

**Comment by LanderU** [comment]
LGTM!

**Review by LanderU — COMMENTED** [review]
LGTM!

**Pull request merged**
