### PR TITLE
Collision detection fcl

### PR DESCRIPTION
**Pull request by anasarrak**

### CODE REVIEW

**Comment by ahcorde** [comment]
are you using this include?

```c++
#include <moveit/logging/logging.h>
```

**Comment by anasarrak** [comment]
It's what we use for the logging, we have created https://github.com/AcutronicRobotics/moveit2/blob/master/moveit_core/logging/include/moveit/logging/logging.h, ROS_DEBUG_NAMED is getting called [here](https://github.com/AcutronicRobotics/moveit2/blob/fe274ec466c2562f48264aa569bd9033817798d7/moveit_core/collision_detection_fcl/src/collision_common.cpp#L122).

But wait! dont merge, I want to try what is specified https://github.com/ros-planning/moveit2/pull/7#discussion_r258819375 by william

**Comment by anasarrak** [comment]
@ahcorde can you check the latest commit please

**Comment by anasarrak** [comment]
@vmayoral check the changes that i've made, maybe is the way to go instead of using the RCUTILS logs

**Comment by ahcorde** [comment]
it seems the way to go right now

```c++
rclcpp::Logger logger = rclcpp::get_logger("collision_detection_fcl");
```

are you gonna add more changes?

**Comment by anasarrak** [comment]
> are you gonna add more changes?

No, you can merge it if it's alright

**Comment by davetcoleman** [comment]
Can we move this PR review process to the main moveit2 repo?

**Pull request merged**
