### PR TITLE
[WIP] continuous integration

### PR DESCRIPTION
**Pull request by LanderU**

### CODE REVIEW

**Comment by vmayoral** [comment]
Thanks @LanderU, let me know once you're ready and I'll review.

**Comment by LanderU** [comment]
I'll close this PR. I've setup travis for this project and I'll start creating everything in a separate branch but using this repo.

**Comment by vmayoral** [comment]
Many thanks @LanderU!

**Comment by vmayoral** [comment]
Feel free to update the README once it's ready please.

**Comment by LanderU** [comment]
Sure!

**Pull request closed without merging**
