### PR TITLE
Compiling moveit_ros/move_group in the CI

### PR DESCRIPTION
**Pull request by ahcorde**
Checking the CI with `moveit_ros_move_group`

### CODE REVIEW

**Comment by LanderU** [comment]
```bash
CMakeFiles/list_move_group_capabilities.dir/src/list_capabilities.cpp.o: In function `pluginlib::ClassLoader<move_group::MoveGroupCapability>::getRegisteredLibraries[abi:cxx11]()':
list_capabilities.cpp:(.text._ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE22getRegisteredLibrariesB5cxx11Ev[_ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE22getRegisteredLibrariesB5cxx11Ev]+0x20): undefined reference to `class_loader::MultiLibraryClassLoader::getRegisteredLibraries[abi:cxx11]() const'
CMakeFiles/list_move_group_capabilities.dir/src/list_capabilities.cpp.o: In function `pluginlib::ClassLoader<move_group::MoveGroupCapability>::unloadLibraryForClass(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
list_capabilities.cpp:(.text._ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE21unloadLibraryForClassERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE21unloadLibraryForClassERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0xb5): undefined reference to `class_loader::MultiLibraryClassLoader::unloadLibrary(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/list_move_group_capabilities.dir/src/list_capabilities.cpp.o: In function `pluginlib::ClassLoader<move_group::MoveGroupCapability>::loadLibraryForClass(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
list_capabilities.cpp:(.text._ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE19loadLibraryForClassERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE19loadLibraryForClassERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x17b): undefined reference to `class_loader::MultiLibraryClassLoader::loadLibrary(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/list_move_group_capabilities.dir/src/list_capabilities.cpp.o: In function `pluginlib::ClassLoader<move_group::MoveGroupCapability>::getAllLibraryPathsToTry(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
list_capabilities.cpp:(.text._ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE23getAllLibraryPathsToTryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_[_ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE23getAllLibraryPathsToTryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_]+0x484): undefined reference to `class_loader::systemLibrarySuffix[abi:cxx11]()'
list_capabilities.cpp:(.text._ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE23getAllLibraryPathsToTryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_[_ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE23getAllLibraryPathsToTryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_]+0x4ed): undefined reference to `class_loader::systemLibrarySuffix[abi:cxx11]()'
list_capabilities.cpp:(.text._ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE23getAllLibraryPathsToTryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_[_ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE23getAllLibraryPathsToTryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_]+0x757): undefined reference to `class_loader::systemLibrarySuffix[abi:cxx11]()'
list_capabilities.cpp:(.text._ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE23getAllLibraryPathsToTryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_[_ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE23getAllLibraryPathsToTryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_]+0x774): undefined reference to `class_loader::systemLibrarySuffix[abi:cxx11]()'
list_capabilities.cpp:(.text._ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE23getAllLibraryPathsToTryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_[_ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE23getAllLibraryPathsToTryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_]+0x796): undefined reference to `class_loader::systemLibrarySuffix[abi:cxx11]()'
CMakeFiles/list_move_group_capabilities.dir/src/list_capabilities.cpp.o:list_capabilities.cpp:(.text._ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE23getAllLibraryPathsToTryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_[_ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE23getAllLibraryPathsToTryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_]+0x7b3): more undefined references to `class_loader::systemLibrarySuffix[abi:cxx11]()' follow
CMakeFiles/list_move_group_capabilities.dir/src/list_capabilities.cpp.o: In function `std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > class_loader::impl::getAvailableClasses<move_group::MoveGroupCapability>(class_loader::ClassLoader const*)':
list_capabilities.cpp:(.text._ZN12class_loader4impl19getAvailableClassesIN10move_group19MoveGroupCapabilityEEESt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EEPKNS_11ClassLoaderE[_ZN12class_loader4impl19getAvailableClassesIN10move_group19MoveGroupCapabilityEEESt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EEPKNS_11ClassLoaderE]+0x2b): undefined reference to `class_loader::impl::getPluginBaseToFactoryMapMapMutex()'
list_capabilities.cpp:(.text._ZN12class_loader4impl19getAvailableClassesIN10move_group19MoveGroupCapabilityEEESt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EEPKNS_11ClassLoaderE[_ZN12class_loader4impl19getAvailableClassesIN10move_group19MoveGroupCapabilityEEESt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EEPKNS_11ClassLoaderE]+0x73): undefined reference to `class_loader::impl::getFactoryMapForBaseClass(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
list_capabilities.cpp:(.text._ZN12class_loader4impl19getAvailableClassesIN10move_group19MoveGroupCapabilityEEESt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EEPKNS_11ClassLoaderE[_ZN12class_loader4impl19getAvailableClassesIN10move_group19MoveGroupCapabilityEEESt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EEPKNS_11ClassLoaderE]+0x142): undefined reference to `class_loader::impl::AbstractMetaObjectBase::isOwnedBy(class_loader::ClassLoader const*) const'
list_capabilities.cpp:(.text._ZN12class_loader4impl19getAvailableClassesIN10move_group19MoveGroupCapabilityEEESt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EEPKNS_11ClassLoaderE[_ZN12class_loader4impl19getAvailableClassesIN10move_group19MoveGroupCapabilityEEESt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EEPKNS_11ClassLoaderE]+0x150): undefined reference to `class_loader::impl::AbstractMetaObjectBase::isOwnedBy(class_loader::ClassLoader const*) const'
CMakeFiles/list_move_group_capabilities.dir/src/list_capabilities.cpp.o: In function `pluginlib::ClassLoader<move_group::MoveGroupCapability>::isClassLoaded(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
list_capabilities.cpp:(.text._ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE13isClassLoadedERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE13isClassLoadedERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x9f): undefined reference to `class_loader::MultiLibraryClassLoader::getAllAvailableClassLoaders() const'
CMakeFiles/list_move_group_capabilities.dir/src/list_capabilities.cpp.o: In function `pluginlib::ClassLoader<move_group::MoveGroupCapability>::~ClassLoader()':
list_capabilities.cpp:(.text._ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEED2Ev[_ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEED5Ev]+0x5b): undefined reference to `class_loader::MultiLibraryClassLoader::~MultiLibraryClassLoader()'
CMakeFiles/list_move_group_capabilities.dir/src/list_capabilities.cpp.o: In function `pluginlib::ClassLoader<move_group::MoveGroupCapability>::ClassLoader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)':
list_capabilities.cpp:(.text._ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEEC2ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_S9_St6vectorIS9_SaIS9_EE[_ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEEC5ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_S9_St6vectorIS9_SaIS9_EE]+0xfc): undefined reference to `class_loader::MultiLibraryClassLoader::MultiLibraryClassLoader(bool)'
list_capabilities.cpp:(.text._ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEEC2ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_S9_St6vectorIS9_SaIS9_EE[_ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEEC5ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_S9_St6vectorIS9_SaIS9_EE]+0x565): undefined reference to `class_loader::MultiLibraryClassLoader::~MultiLibraryClassLoader()'
CMakeFiles/list_move_group_capabilities.dir/src/list_capabilities.cpp.o: In function `pluginlib::ClassLoader<move_group::MoveGroupCapability>::refreshDeclaredClasses()':
list_capabilities.cpp:(.text._ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE22refreshDeclaredClassesEv[_ZN9pluginlib11ClassLoaderIN10move_group19MoveGroupCapabilityEE22refreshDeclaredClassesEv]+0xd0): undefined reference to `class_loader::MultiLibraryClassLoader::getRegisteredLibraries[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
```

**Comment by ahcorde** [comment]
I removed manually `class_loader` from `/opt/ros/dashing/` and I installed `https://github.com/ros/class_loader/ -b ros2`

Then in my machine compiles without problems

**Comment by ahcorde** [comment]
It's strange because the repository is correct in https://github.com/ros2/ros2/blob/master/ros2.repos#L102

I don't really know which version is been compiled for the packages.

**Comment by LanderU** [comment]
Applied the changes, and CI running again. Works perfectly locally.

**Review by LanderU — APPROVED** [review]

**Pull request merged**
