### PR TITLE
Port Dynamics solver

### PR DESCRIPTION
**Pull request by anasarrak**

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Comment by anasarrak** [comment]
The CI didn't pass for IOS
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```
but for the PR has passed

**Comment by LanderU** [comment]
I'll have a look.

**Comment by LanderU** [comment]
https://travis-ci.org/AcutronicRobotics/moveit2/jobs/501962350

**Comment by anasarrak** [comment]
This can be merged then

**Pull request merged**
