### PR TITLE
Port query_planners_service_capability

### PR DESCRIPTION
**Pull request by anasarrak**
This will fail since its waiting for https://github.com/AcutronicRobotics/moveit2/pull/39

Ported: 
 - Updated move_group cmakelist to build just query_planners_service_capability 
 - Update planning and perception cmakelists
 - Port move_group_capability

### CODE REVIEW

**Comment by anasarrak** [comment]
This depends from planning_scene_monitor, the CI will not pass

**Comment by vmayoral** [comment]
Rebased the repository but this is still not building for me:
```bash
colcon build --merge-install --packages-select moveit_ros_move_group
Starting >>> moveit_ros_move_group
--- stderr: moveit_ros_move_group
CMake Warning at /Users/victor/ros2_moveit_ws/install/share/moveit_ros_planning/cmake/ament_cmake_export_libraries-extras.cmake:116 (message):
  Package 'moveit_ros_planning' exports library
  'moveit_constraint_sampler_manager_loader' which couldn't be found
Call Stack (most recent call first):
  /Users/victor/ros2_moveit_ws/install/share/moveit_ros_planning/cmake/moveit_ros_planningConfig.cmake:38 (include)
  CMakeLists.txt:15 (find_package)


CMake Warning at /Users/victor/ros2_moveit_ws/install/share/moveit_ros_planning/cmake/ament_cmake_export_libraries-extras.cmake:116 (message):
  Package 'moveit_ros_planning' exports library
  'moveit_trajectory_execution_manager' which couldn't be found
Call Stack (most recent call first):
  /Users/victor/ros2_moveit_ws/install/share/moveit_ros_planning/cmake/moveit_ros_planningConfig.cmake:38 (include)
  CMakeLists.txt:15 (find_package)


CMake Warning at /Users/victor/ros2_moveit_ws/install/share/moveit_ros_planning/cmake/ament_cmake_export_libraries-extras.cmake:116 (message):
  Package 'moveit_ros_planning' exports library 'moveit_plan_execution' which
  couldn't be found
Call Stack (most recent call first):
  /Users/victor/ros2_moveit_ws/install/share/moveit_ros_planning/cmake/moveit_ros_planningConfig.cmake:38 (include)
  CMakeLists.txt:15 (find_package)


In file included from In file included from /Users/victor/ros2_moveit_ws/src/moveit2/moveit_ros/move_group/src/default_capabilities/query_planners_service_capability.cpp/Users/victor/ros2_moveit_ws/src/moveit2/moveit_ros/move_group/src/move_group_capability.cpp:37:
In file included from /Users/victor/ros2_moveit_ws/src/moveit2/moveit_ros/move_group/include/moveit/move_group/move_group_capability.h:41:
In file included from /Users/victor/ros2_moveit_ws/install/include/moveit/planning_scene_monitor/planning_scene_monitor.h:40:
/Users/victor/ros2_ws/install/tf2_ros/include/tf2_ros/message_filter.h::40:1037::
 In file included from fatal error/Users/victor/ros2_moveit_ws/src/moveit2/moveit_ros/move_group/src/default_capabilities/query_planners_service_capability.h: :'message_filters/connection.h' file not found40
:
In file included from /Users/victor/ros2_moveit_ws/src/moveit2/moveit_ros/move_group/include/moveit/move_group/move_group_capability.h:41:
In file included from /Users/victor/ros2_moveit_ws/install/include/moveit/planning_scene_monitor/planning_scene_monitor.h:40:
/Users/victor/ros2_ws/install/tf2_ros/include/tf2_ros/message_filter.h:40:10: fatal error: 'message_filters/connection.h' file not found
#include <message_filters/connection.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#include <message_filters/connection.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
1 error generated.
make[2]: make[2]: *** [CMakeFiles/moveit_move_group_capabilities_base.dir/src/move_group_capability.cpp.o] Error 1*** [CMakeFiles/moveit_move_group_default_capabilities.dir/src/default_capabilities/query_planners_service_capability.cpp.o] Error 1

make[1]: *** [CMakeFiles/moveit_move_group_capabilities_base.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/moveit_move_group_default_capabilities.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< moveit_ros_move_group	[ Exited with code 2 ]
```

**Comment by anasarrak** [comment]
I fixed the problems that I was having with the following commit https://github.com/AcutronicRobotics/moveit2/pull/41/commits/64f660c38f78251d0e1eb34e7f4bb2b3395233fb, but the problem that you are having is related to message_filters

**Comment by anasarrak** [comment]
> ```shell
> CMake Warning at /Users/victor/ros2_moveit_ws/install/share/moveit_ros_planning/cmake/ament_cmake_export_libraries-extras.cmake:116 (message):
>   Package 'moveit_ros_planning' exports library 'moveit_plan_execution' which
>   couldn't be found
> ```

moveit_plan_execution is needed, but the PR is already opened on https://github.com/AcutronicRobotics/moveit2/pull/46 and this one depends from https://github.com/AcutronicRobotics/moveit2/pull/45

**Comment by anasarrak** [comment]
New PR on https://github.com/AcutronicRobotics/moveit2/pull/53 to replace this

**Pull request closed without merging**
