### PR TITLE
Port Common_planning_interface_objects to ROS2

### PR DESCRIPTION
**Pull request by anasarrak**
Adding the clang-format to the CMakelist made the whole file a mess... I had to fix it manually

### CODE REVIEW

**Comment by anasarrak** [comment]
```
/root/moveit2/moveit_core/collision_detection/src/collision_tools.cpp:281:21: error: ‘toMsg2’ is not a member of ‘tf2’
   msg.normal = tf2::toMsg2(contact.normal);
```
CI failing

**Comment by LanderU** [comment]
https://travis-ci.org/AcutronicRobotics/moveit2/jobs/519757291#L4952

**Comment by vmayoral** [comment]
Thanks for looking at this @LanderU, how can I help from this point on? should we split the PRs?

**Comment by LanderU** [comment]
Not sure how to procede here. But, looks like is not able to find moveit_ros_planning:

```bash
CMake Warning at /opt/ws_moveit/install/share/moveit_ros_planning/cmake/ament_cmake_export_libraries-extras.cmake:116 (message):
  Package 'moveit_ros_planning' exports library 'moveit_plan_execution' which
  couldn't be found
Call Stack (most recent call first):
  /opt/ws_moveit/install/share/moveit_ros_planning/cmake/moveit_ros_planningConfig.cmake:38 (include)
  CMakeLists.txt:16 (find_package)
/root/moveit2/moveit_ros/planning_interface/common_planning_interface_objects/src/common_objects.cpp:38:10: fatal error: moveit/robot_model_loader/robot_model_loader.h: No such file or directory
 #include <moveit/robot_model_loader/robot_model_loader.h>
```

**Comment by anasarrak** [comment]
Now it should work, let's wait the CI

**Review by LanderU — APPROVED** [review]

**Review by ahcorde — APPROVED** [review]

**Pull request merged**
