### PR TITLE
Re-enable Travis in OS X

### PR DESCRIPTION
**Pull request by vmayoral**
Not to be merged until Travis passes in both operating systems.

### CODE REVIEW

**Comment by vmayoral** [comment]
Failing in OS X https://travis-ci.org/AcutronicRobotics/moveit2/jobs/522551826#L5137

I've confirmed that I get local issues as well, will look it up.

**Comment by vmayoral** [comment]
Now failing at:

```bash
In file included from /Users/victor/ros2_moveit_ws/src/moveit2/moveit_ros/move_group/src/default_capabilities/move_action_capability.cpp:37:
/Users/victor/ros2_moveit_ws/src/moveit2/moveit_ros/move_group/src/default_capabilities/move_action_capability.h:43:10: fatal error: 'moveit_msgs/action/move_group.hpp' file not found
#include "moveit_msgs/action/move_group.hpp"
```

**Comment by vmayoral** [comment]
@LanderU this line https://github.com/AcutronicRobotics/moveit2/pull/54/commits/017e1cd2822aa2ed6799322793b8da13c437a6bc#diff-354f30a63fb0907d4ad57269548329e3R28 has been removed from .travis.yaml? Has this been on purpose? Isn't it required by our CI?

**Comment by LanderU** [comment]
```bash
0.00sTest log of build/moveit_ros_move_group/test_results/moveit_ros_move_group/lint_cmake.xunit.xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite
  name="moveit_ros_move_group.lint_cmake"
  tests="2"
  failures="2"
  time="0.002"
>
  <testcase
    name="whitespace/mismatch (CMakeLists.txt:28)"
    classname="moveit_ros_move_group.lint_cmake"
  >
      <failure message="Mismatching spaces inside () after command"/>
  </testcase>
  <testcase
    name="whitespace/mismatch (CMakeLists.txt:38)"
    classname="moveit_ros_move_group.lint_cmake"
  >
      <failure message="Mismatching spaces inside () after command"/>
  </testcase>
  <system-out>Checked files:
* CMakeLists.txt</system-out>
</testsuite>
build/moveit_ros_move_group/test_results/moveit_ros_move_group/lint_cmake.xunit.xml: 2 tests, 0 errors, 2 failures, 0 skipped
```

**Comment by LanderU** [comment]
> @LanderU this line 017e1cd#diff-354f30a63fb0907d4ad57269548329e3R28 has been removed from .travis.yaml? Has this been on purpose? Isn't it required by our CI?

Now you can locate it on .travis.linux.env and .travis.osx.env. We can set it again on the yml file.

**Comment by vmayoral** [comment]
Found that my moveit_msgs was not updated. When updated and compiling moveit_msgs again:
```bash
=> colcon build --merge-install --cmake-args -DBUILD_TESTING:BOOL=OFF --packages-select moveit_msgs
Starting >>> moveit_msgs
[Processing: moveit_msgs]
[Processing: moveit_msgs]
[Processing: moveit_msgs]
--- stderr: moveit_msgs
Action interface 'moveit_msgs/RobotTrajectory' contains an unknown field type: moveit_msgs/RobotTrajectory trajectory
make[2]: *** [rosidl_typesupport_cpp/moveit_msgs/action/execute_trajectory__type_support.cpp] Error 1
make[1]: *** [CMakeFiles/moveit_msgs__rosidl_typesupport_cpp__generate_actions.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
make: INTERNAL: Exiting with 9 jobserver tokens available; should be 8!
---
Failed   <<< moveit_msgs	[ Exited with code 2 ]

Summary: 0 packages finished [1min 50s]
  1 package failed: moveit_msgs
  1 package had stderr output: moveit_msgs
The file /Users/victor/ros2_moveit_ws/None does not exist.
```

**Comment by vmayoral** [comment]
Similar with another package:
```bash
--- stderr: object_recognition_msgs
Action interface 'object_recognition_msgs/RecognizedObjectArray' contains an unknown field type: object_recognition_msgs/RecognizedObjectArray recognized_objects
make[2]: *** [rosidl_typesupport_cpp/object_recognition_msgs/action/object_recognition__type_support.cpp] Error 1
make[1]: *** [CMakeFiles/object_recognition_msgs__rosidl_typesupport_cpp__generate_actions.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
```

I seem to have an issue with actions in my ws compiled from sources. I will retry to build my ros2 setup from sources again.

**Comment by LanderU** [comment]
Make sure that you've patch4 on your ws.

**Comment by vmayoral** [comment]
> Make sure that you've patch4 on your ws.

I didn't, I'm now trying out with https://discourse.ros.org/t/ros-2-dashing-diademata-call-for-testing-and-package-releases/8819 and latest instructions https://index.ros.org/doc/ros2/Installation/OSX-Development-Setup/

**Comment by LanderU** [comment]
> The job exceeded the maximum time limit for jobs, and has been terminated.

https://travis-ci.org/AcutronicRobotics/moveit2/jobs/522562529

**Comment by LanderU** [comment]
https://travis-ci.org/AcutronicRobotics/moveit2/jobs/522562521

It works for OS X

**Comment by vmayoral** [comment]
Shall we merge this or wait for Linux CI?

**Comment by LanderU** [comment]
LGTM! The problem with Linux, is that not passing the test probably because clang format.

**Review by LanderU — APPROVED** [review]

**Comment by vmayoral** [comment]
Cool, let us look at it on master then

**Pull request merged**
