### PR TITLE
Port Collision distance field 

### PR DESCRIPTION
**Pull request by anasarrak**

### CODE REVIEW

**Comment by anasarrak** [comment]
Some relevant things to note on some of the commits:
 - __[WallTime](https://github.com/AcutronicRobotics/moveit2/blob/50cbb936b814dcc486e576dd54f8633b7a469efb/moveit_core/collision_distance_field/src/collision_world_distance_field.cpp#L475)__ : Instead of using ros::WallTime, we should be using [std::chrono::system_clock::now](https://en.cppreference.com/w/cpp/chrono/system_clock/now) since it's not implemented on RCLCPP yet. Mentioned by williams on https://github.com/ros-planning/moveit2/issues/31#issuecomment-468238280
- __[ROS_DEBUG/WARN/ERROR/INFO_STREAM](http://docs.ros.org/jade/api/rosconsole/html/macros__generated_8h.html#abe3fd4f1f711e3046f7c3a8e3f5757b0)__: There is not yet an implementation for rclcpp, I have replaced it this [way](https://github.com/AcutronicRobotics/moveit2/blob/3e710d81835521fc120cb6664fd374466f5b11dd/moveit_core/collision_distance_field/src/collision_world_distance_field.cpp#L516)  
- __[ROS_DEBUG_COND](http://docs.ros.org/jade/api/rosconsole/html/macros__generated_8h.html#adfcd1f405714d4edebd32b25d932e3fe)__ not implemented yet, used [this](https://github.com/AcutronicRobotics/moveit2/blob/3e710d81835521fc120cb6664fd374466f5b11dd/moveit_core/collision_distance_field/src/collision_robot_distance_field.cpp#L173) directly

**Comment by anasarrak** [comment]
CI not passed becuase this pr was still open https://github.com/AcutronicRobotics/geometric_shapes/pull/1#event-2171748583

**Comment by vmayoral** [comment]
Issues in OS X 10.14.3:
```bash
/Users/victor/ros2_moveit_ws/src/moveit2/moveit_core/collision_detection/src/collision_matrix.cpp:71:11: error: call to member function 'setEntry' is ambiguous
          setEntry(msg.entry_names[i], msg.entry_names[j], msg.entry_values[i].enabled[j]);
          ^~~~~~~~
/Users/victor/ros2_moveit_ws/src/moveit2/moveit_core/collision_detection/include/moveit/collision_detection/collision_matrix.h:144:8: note: candidate function
  void setEntry(const std::string& name1, const std::string& name2, bool allowed);
       ^
/Users/victor/ros2_moveit_ws/src/moveit2/moveit_core/collision_detection/include/moveit/collision_detection/collision_matrix.h:152:8: note: candidate function
  void setEntry(const std::string& name1, const std::string& name2, const DecideContactFn& fn);
       ^
/Users/victor/ros2_moveit_ws/src/moveit2/moveit_core/collision_detection/include/moveit/collision_detection/collision_matrix.h:172:8: note: candidate function not viable: no known conversion from 'const std::__1::__vector_base<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >::value_type' (aka 'const std::__1::basic_string<char>') to 'const std::vector<std::string>' (aka 'const vector<basic_string<char, char_traits<char>, allocator<char> > >') for 2nd argument
  void setEntry(const std::string& name, const std::vector<std::string>& other_names, bool allowed);
       ^
/Users/victor/ros2_moveit_ws/src/moveit2/moveit_core/collision_detection/include/moveit/collision_detection/collision_matrix.h:181:8: note: candidate function not viable: no known conversion from 'const std::__1::__vector_base<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >::value_type' (aka 'const std::__1::basic_string<char>') to 'const std::vector<std::string>' (aka 'const vector<basic_string<char, char_traits<char>, allocator<char> > >') for 1st argument
  void setEntry(const std::vector<std::string>& names1, const std::vector<std::string>& names2, bool allowed);
       ^
/Users/victor/ros2_moveit_ws/src/moveit2/moveit_core/collision_detection/include/moveit/collision_detection/collision_matrix.h:162:8: note: candidate function not viable: requires 2 arguments, but 3 were provided
  void setEntry(const std::string& name, bool allowed);
       ^
/Users/victor/ros2_moveit_ws/src/moveit2/moveit_core/collision_detection/include/moveit/collision_detection/collision_matrix.h:188:8: note: candidate function not viable: requires single argument 'allowed', but 3 arguments were provided
  void setEntry(bool allowed);
       ^
```

**Comment by vmayoral** [comment]
```bash
 RCLCPP_DEBUG(logger, "Non-group joint %p will be checked for state changes", *name_iter);
                                                                                   ^
/Users/victor/ros2_moveit_ws/src/moveit2/moveit_core/collision_distance_field/src/collision_robot_distance_field.cpp:1050:116: error: cannot pass object of non-trivial type 'const std::string' (aka 'const basic_string<char, char_traits<char>, allocator<char> >') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
```

**Comment by vmayoral** [comment]
```bash
In file included from /Users/victor/ros2_moveit_ws/src/moveit2/moveit_core/collision_distance_field/src/collision_distance_field_types.cpp:37:
In file included from /Users/victor/ros2_moveit_ws/src/moveit2/moveit_core/collision_distance_field/include/moveit/collision_distance_field/collision_distance_field_types.h:48:
In file included from /Users/victor/ros2_moveit_ws/install/include/geometric_shapes/bodies.h:45:
In file included from /Users/victor/ros2_moveit_ws/install/include/eigen_stl_containers/eigen_stl_containers.h:40:
In file included from /Users/victor/ros2_moveit_ws/install/include/eigen_stl_containers/eigen_stl_vector_container.h:41:
In file included from /usr/local/include/eigen3/Eigen/Geometry:44:
/usr/local/include/eigen3/Eigen/src/Geometry/Transform.h:331:5: error: static_assert failed "YOU_PERFORMED_AN_INVALID_TRANSFORMATION_CONVERSION"
    EIGEN_STATIC_ASSERT(EIGEN_IMPLIES(OtherMode==int(Affine)||OtherMode==int(AffineCompact), Mode!=int(Isometry)),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/eigen3/Eigen/src/Core/util/StaticAssert.h:33:40: note: expanded from macro 'EIGEN_STATIC_ASSERT'
    #define EIGEN_STATIC_ASSERT(X,MSG) static_assert(X,#MSG);
                                       ^             ~
/Users/victor/ros2_moveit_ws/src/moveit2/moveit_core/collision_distance_field/src/collision_distance_field_types.cpp:282:41: note: in instantiation of function template specialization 'Eigen::Transform<double, 3, 1, 0>::Transform<2, 0>' requested here
    bodies_.addBody(shapes[i]->clone(), poses[i], padding);
```

**Comment by vmayoral** [comment]
@anasarrak this is failing https://travis-ci.org/AcutronicRobotics/moveit2/jobs/501048363

**Comment by vmayoral** [comment]
Not very sure how you tested this out to be honest.

**Comment by vmayoral** [comment]
Requires changes, refer to https://github.com/AcutronicRobotics/moveit2/issues/19#issuecomment-469074301

**Comment by anasarrak** [comment]
Closing this, the actual pr https://github.com/AcutronicRobotics/moveit2/pull/20.

**Pull request closed without merging**
